version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    restart: on-failure
    depends_on:
      - db
    command: >
      /wait-for-it.sh db:3306 -- java -jar app.jar

  db:
    image: mysql/mysql-server
    ports:
      - "3308:3306"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - app
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


